services:
    app.admin.product:
        class: Ch\ShopBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Shop", label: "Products" }
        arguments:
            - ~
            - Ch\ShopBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [ChShopBundle]]
        public: true

    app.admin.category:
            class: Ch\ShopBundle\Admin\CategoryAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Shop", label: "Categories" }
            arguments:
                - ~
                - Ch\ShopBundle\Entity\Category
                - ~
            calls:
                - [ setTranslationDomain, [ChShopBundle]]
            public: true