<?php

namespace Ch\ShopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findOneByIdJoinedToCategory($productId)
    {
       $query = $this->createQueryBuilder('c')
            ->innerJoin('c.products', 'c')
            ->where('c.id = :product_id')
            ->setParameter('product_id', 5)
            ->getQuery()->getResult();

        $this->db->select('users.name');
        $this->db->from('users');
        $this->db->join('user_group', 'user_group.user_id = users.id');
        $this->db->join('groups', 'groups.id = user_group.group_id');
        $this->db->where('user_group.group_id', 3);
    }
}
