<?php

namespace Ch\ShopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findOneByIdJoinedToCategory($productId)
    {
        /*$qb= $this->createQueryBuilder('c')
           ->from('Ch\ShopBundle\Entity\Category', 'c')
           ->innerJoin('product_category c',  Join::ON, 'c.id = product_category.category_id')
           ->where('product_category.product_id = :product');


        $qb->setParameters(array('product' => $productId ));

        $query = $qb->getQuery();

         */

        $query = $this->createQueryBuilder('c')
            ->addSelect('product_category.product_id')
            ->from('Ch\ShopBundle\Entity\Category', 'cat')
            ->join('cat.name product_category')
            ->where('product_category.product_id=1');

        //$categories= $query->getResult();
        return $query->getQuery()->getResult();
    }
}
